### ISSUE TITLE
Differents length of courses ?

### ISSUE THREAD

**Issue by Pascal66** [shridattz/dynamicTimeTable#2]
Can you give me a clue about how to manage diffferents lentgh of courses ?

**Comment by shridattz** [comment]
Check the `Subject` class, it expects the number of lectures per week. You could fiddle around in the `Initialization` Class to get what you desire.

**Comment by shridattz** [comment]
Close this issue if it works for you

**Comment by Pascal66** [comment]
I want to achieve that.
http://works.bepress.com/cgi/viewcontent.cgi?article=1372&context=jeremy_straub
I'm not sure on how to work with subject class..
Btw i can close issue if you want

**Comment by Pascal66** [comment]
ty for the help
